### ISSUE TITLE
lower author infos slipped

### ISSUE THREAD

**Issue by lehkost** [weltliteratur/blog#3]
they used to be on the right side of the gravatars…

**Comment by rjoberon** [comment]
This was probably caused by commit #e9f4a24542e389e960895d4978d57301da191c54 though commit #5381b79 could not solve the problem. Without a heading, `<section>` is not valid, thus I aimed at fixing this issue.

**Comment by lehkost** [comment]
mea culpa, removed some gibberish in the main css file which fixes #3…
